# Generated by Django 3.1.7 on 2021-04-29 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='times_disliked',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='times_liked',
        ),
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 19, 13, 518454)),
        ),
    ]
